<a href="https://colab.research.google.com/github/Srinjoy-Santra/Computer-Security/blob/master/3_traditional_symmetric_key_ciphers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Traditional Symmetric Key Cipher

The contents are based on the book [Cryptography and Network Security by Forouzan](https://www.amazon.in/Crypt-Network-Security-Forouzan/dp/9339220943/ref=sr_1_1?crid=2KX4D7TQ5H46O&dchild=1&keywords=cryptography+and+network+security+forouzan&qid=1589793253&sprefix=cryptogr%2Caps%2C379&sr=8-1)

- Strictly for educational purpose.


If P is the plaintext, C is the ciphertext, and K is the key, 
- Encryption: $C = E_k(P)$
- Decryption: $P = D_k(C)$
- In which $D_k(E_k(x)) = E_k(D_k(x)) = x$

We assume that Bob creates P1; we prove that P1 = P.
![symmetric key cipher](https://drive.google.com/uc?id=1oAw-zvsF7ftzWE0ozM0nM8CNj4hGzUZF)


#### Kerckhoff's Principle
One should always assume that the adversary, Eve, knows the encryption/decryption algorithm. The resistance of the cipher to attack must be based only on the secrecy of the key. 

#### Terminologies
As cryptography is the science and art of creating secret codes,
cryptanalysis is the science and art of breaking those codes. 

#### Cryptanalysis Attacks

1. Ciphertext-Only Attack ![Ciphertext-Only Attack](https://drive.google.com/uc?id=1mXe8-gpK6SvhbT56WhKzcIm21I36V953)
2. Known-Plaintext Attack ![Known-Plaintext Attack](https://drive.google.com/uc?id=1E7VpOzISDQtE0itcjwpl9O3qvAfG38KP)
3. Chosen-Plaintext Attack ![Chosen-Plaintext Attack](https://drive.google.com/uc?id=1t8HzXQPIrlTUNS_MR1XbkRvgJmIDZlm2)
4. Chosen-Ciphertext Attack ![Chosen-Ciphertext Attack](https://drive.google.com/uc?id=1F7QyqI2cRp-0PRUIwN0H7RZ1M-vakbV1)



## Substitution Ciphers
A **substitution cipher** replaces one symbol with another.
It can be categorized as 

1.   Monoalphabetic Ciphers
2.   Polyalphabetic Ciphers

In **monoalphabetic substitution**, the relationship between a symbol in the plaintext to a symbol in the ciphertext is always one-to-one.

It can be categorized into

1.   Additive/Shift/Ceaser cipher
2.   Multiplicative cipher
3.   Affine cipher

**Additive cipher** : plaintext, ciphertext, and key are integers in Z26.










In [23]:
# Additive cipher
def ltr_to_num(ltr):
  return ord(ltr) - 97

def num_to_ltr(num):
  return chr(num + 97)

class AdditiveCipher:
  def encrypt(self, plaintext, key=3):
    ciphertext = ''
    for p in plaintext:
      ciphertext += num_to_ltr( ( ltr_to_num(p) + key ) % 26 )
    return ciphertext

  def decrypt(self, ciphertext, key=3):
    plaintext = ''
    for p in ciphertext:
      plaintext += num_to_ltr( ( ltr_to_num(p) - key ) % 26 )
    return plaintext

print("encrypt 'hello', key=15, =>",AdditiveCipher().encrypt('hello', 15))
print("encrypt 'wtaad', key=15, =>",AdditiveCipher().decrypt('wtaad', 15))
print("encrypt 'caesar', key=3, =>",AdditiveCipher().encrypt('caesar'))

encrypt 'hello', key=15, => wtaad
encrypt 'wtaad', key=15, => hello
encrypt 'caesar', key=3, => fdhvdu


Eve has intercepted the ciphertext “UVACLYFZLJBYL”. Show how she can use a brute-force attack to break the cipher

In [0]:
ciphertext = 'UVACLYFZLJBYL'.lower()

In [25]:
for key in range(1,10):
  print("decrypt, key = "+str(key)+"=>",AdditiveCipher().decrypt(ciphertext,key))

decrypt, key = 1=> tuzbkxeykiaxk
decrypt, key = 2=> styajwdxjhzwj
decrypt, key = 3=> rsxzivcwigyvi
decrypt, key = 4=> qrwyhubvhfxuh
decrypt, key = 5=> pqvxgtaugewtg
decrypt, key = 6=> opuwfsztfdvsf
decrypt, key = 7=> notverysecure
decrypt, key = 8=> mnsudqxrdbtqd
decrypt, key = 9=> lmrtcpwqcaspc


Eve has intercepted the following ciphertext. Using a statistical attack, find the plaintext.
XLILSYWIMWRSAJSVWEPIJSVJSYVQMPPMSRHSPPEVWMXMWASVX-LQSVILY-VVCFIJSVIXLIWIPPIVVIGIMZIWQSVISJJIVW 

In [26]:
ciphertext = 'XLILSYWIMWRSAJSVWEPIJSVJSYVQMPPMSRHSPPEVWMXMWASVX-LQSVILY-VVCFIJSVIXLIWIPPIVVIGIMZIWQSVISJJIVW'.lower()
freq = {i : ciphertext.count(i) for i in set(ciphertext)} 
print('Frequencies ', freq)

Frequencies  {'c': 1, 's': 12, 'm': 6, 'j': 6, 'h': 1, 'l': 5, 'i': 14, 'w': 8, 'r': 2, 'v': 13, 'p': 7, 'a': 2, 'e': 2, 'q': 3, 'f': 1, 'y': 3, 'g': 1, 'z': 1, '-': 2, 'x': 4}


'i' is the most common, may be 'e'.
Since, I = 14, V =13, S =12

In [27]:
dif = ord('i')-ord('e')
print('diff', dif)
print('decrypt', AdditiveCipher().decrypt(ciphertext, dif))

diff 4
decrypt thehouseisnowforsaleforfourmilliondollarsitiswortwhmorehuwrrybeforethesellerreceivesmoreoffers


**Mulltiplicative Cipher**
the plaintext and ciphertext are integers in Z26; the key is an integer in Z26* .
Z26* set has only 12 members: 1, 3, 5, 7, 9, 11, 15, 17, 19, 21, 23, 25.
Others have one-to-many mapping thus decryption is not possible.



In [0]:
# Multiplicative inverse https://www.geeksforgeeks.org/multiplicative-inverse-under-modulo-m/
def modInverse(a, m=26) : 
    m0 = m 
    y = 0
    x = 1
  
    if (m == 1) : 
        return 0
  
    while (a > 1) : 
  
        # q is quotient 
        q = a // m 
  
        t = m 
  
        # m is remainder now, process 
        # same as Euclid's algo 
        m = a % m 
        a = t 
        t = y 
  
        # Update x and y 
        y = x - q * y 
        x = t 
  
  
    # Make x positive 
    if (x < 0) : 
        x = x + m0 
  
    return x 

In [29]:
class MultiplicativeCipher:
  def encrypt(self, plaintext, key):
    ciphertext = ''
    for p in plaintext:
      ciphertext += num_to_ltr( int( ltr_to_num(p) * key ) % 26 )
    return ciphertext

  def decrypt(self, ciphertext, key):
    plaintext = ''
    for p in ciphertext:
      plaintext += num_to_ltr( round( ltr_to_num(p) * modInverse(key) ) % 26 )
    return plaintext

print("encrypt 'hello', key=7, =>", MultiplicativeCipher().encrypt('hello', 7))
print("encrypt 'xczzu', key=7, =>", MultiplicativeCipher().decrypt('xczzu', 7))

encrypt 'hello', key=7, => xczzu
encrypt 'xczzu', key=7, => hello


### Affine Cipher
the keys
k1 is an integer in Z26* and k2 is an integer in Z26.

*   C = (P X k1 + k2) mod26
*   P = ( (C-k2) * (1/k1) ) mod26

The affine cipher uses a pair of keys in which the first key is from Z26* and the second is from Z26.


In [30]:
class AffineCipher:
  def encrypt(self, plaintext, keys):
    k1, k2 = keys
    ciphertext = ''
    for p in plaintext:
      ciphertext += num_to_ltr( (int(ltr_to_num(p))*k1 + k2) % 26 )
    return ciphertext

  def decrypt(self, ciphertext, keys):
    k1, k2 = keys
    plaintext = ''
    for p in ciphertext:
      plaintext += num_to_ltr( round( (ltr_to_num(p) - k2) * modInverse(k1) ) % 26 )
    return plaintext

print("encrypt 'hello', key=7,2 =>", AffineCipher().encrypt('hello', [7,2]))
print("encrypt 'zebbw', key=7,2 =>", AffineCipher().decrypt('zebbw', [7,2]))

encrypt 'hello', key=7,2 => zebbw
encrypt 'zebbw', key=7,2 => hello


### Monoalphabetic Substitution Cipher
Affine ciphaer have small key domains, therfore are vulnrable to brute-force attack

A better solution is to create a mapping between each plaintext character and the corresponding ciphertext character. 

In [0]:
pt_to_ct = {
    'a':'n',
    'b':'o',
    'c':'a',
    'd':'t',
    'e':'r',
    'f':'b',
    'g':'e',
    'h':'c',
    'i':'f',
    'j':'u',
    'k':'x',
    'l':'d',
    'm':'q',
    'n':'g',
    'o':'y',
    'p':'l',
    'q':'k',
    'r':'h',
    's':'v',
    't':'i',
    'u':'j',
    'v':'m',
    'w':'p',
    'x':'z',
    'y':'s',
    'z':'w'
}

In [32]:
plaintext = 'this message is easy to encrypt but hard to find the key'
ciphertext = ''
for p in plaintext.replace(' ',''):
  ciphertext += pt_to_ct[p]
print(plaintext + "\n" + ciphertext)

this message is easy to encrypt but hard to find the key
icfvqrvvnerfvrnvsiyrgahsliojicnhtiybfgticrxrs


### Polyalphabetic Ciphers

In polyalphabetic substitution, each occurrence of a character may have a different substitute. The relationship between a character in the plaintext to a character in the ciphertext is one-to-many. 

### Auto Key cipher

*   P = p1p2p3...
*   C = c1c2c3...
*   k = (k1,p1,p2,...)

Ci = (Pi + ki) mod26
Pi = (Ci - ki) mod26


In [33]:
class AutoKeyCipher:
  def encrypt(self, plaintext, key):
    # convert to lowercase,
    # remove spaces
    plaintext = plaintext.lower().replace(' ','')
    # convert string to list of chars [only for Python version >3.5]
    # convert chars from ascii to digits
    plaintext = [ltr_to_num(x) for x in [*plaintext]]
    # add initial ket to keystream
    keystream = [key]
    # update keystream with plaintext digits subsequently
    keystream.extend(plaintext[:len(plaintext) -1])
    # add digits from plaintext and keystream
    # find modulo 26
    # convert digit to letter 
    ciphertext =  [num_to_ltr(sum(x)%26) for x in zip(plaintext, keystream)]
    # convert list to string
    ciphertext = ''.join(ciphertext)
    return ciphertext

  def decrypt(self, ciphertext, key):
    plaintext = ''
    # convert string to list of chars [only for >3.5]
    # convert digits to ascii  
    for p in ciphertext:
      key = (ltr_to_num(p) - key%26)%26
      plaintext += num_to_ltr(key)

    return plaintext

print("encrypt 'Attack is today', key=12 =>", AutoKeyCipher().encrypt('Attack is today', 12))
print("decrypt 'mtmtcmsalhrdy', key=12 =>", AutoKeyCipher().decrypt('mtmtcmsalhrdy', 12))



encrypt 'Attack is today', key=12 => mtmtcmsalhrdy
decrypt 'mtmtcmsalhrdy', key=12 => attackistoday


### Playfair cipher

[Hindi Video](https://www.youtube.com/watch?v=1ZPr1O-1IkQ)

In [0]:
import numpy as np

In [35]:
default_keyword = 'lgdba qmhec urnif xvsok zywtp'.replace(' ','')
def create_pc_key(keyword=default_keyword):
  
  # replace j with i (both are used intechangeably)
  # https://stackoverflow.com/questions/1653970/does-python-have-an-ordered-set
  # create an ordered set of keyword string chars
  keyword = list(dict.fromkeys([*keyword.replace('j','i')]).keys())

  # remove characters already in keyword
  z = [*'abcdefghiklmnopqrstuvwxyz']

  for y in keyword:
    if y in z: z.remove(y)
 
  arr = np.zeros((5,5), dtype=np.int8)
  j=0
  for i in range(25):
    try:
      k = keyword[i]
    except:
      if len(z) is not 0:
        k = z[j]
        j+=1
    
    arr[i//5,i%5]=ltr_to_num(k)

  
  return arr

print(create_pc_key('playfairexample'))
print(create_pc_key())
print(create_pc_key('pascal'))

[[15 11  0 24  5]
 [ 8 17  4 23 12]
 [ 1  2  3  6  7]
 [10 13 14 16 18]
 [19 20 21 22 25]]
[[11  6  3  1  0]
 [16 12  7  4  2]
 [20 17 13  8  5]
 [23 21 18 14 10]
 [25 24 22 19 15]]
[[15  0 18  2 11]
 [ 1  3  4  5  6]
 [ 7  8 10 12 13]
 [14 16 17 19 20]
 [21 22 23 24 25]]


In [36]:
class PlayfairCipher:
  def encrypt(self, plaintext, key, dummy='x'):
    # convert to lowercase,
    # remove spaces
    plaintext = plaintext.lower().replace(' ','')
    # string to list of chars
    plaintext = [*plaintext]
    
    #search for repeating characters
    i=0
    while True:
      try:
        # Add dummy char for consecutive repeating char
        if i>0 and plaintext[i] == plaintext[i-1]:
          plaintext.insert(i,dummy)
        i+=1
      except:
        break  
    # Add dummy char for odd length
    if i % 2 is 1:
          plaintext.insert(i,dummy)

    ciphertext = ""
    for i in range(1,len(plaintext), 2):
      prv = ltr_to_num(plaintext[i-1])
      prv_r,prv_c = np.where(key == ('i' if prv == 'j' else prv))
      nxt = ltr_to_num(plaintext[i])
      nxt_r,nxt_c = np.where(key == ('i' if nxt == 'j' else nxt))
      # both in same row
      if prv_r == nxt_r:
        ciphertext += num_to_ltr(key[prv_r,(prv_c+1)%5])
        ciphertext += num_to_ltr(key[nxt_r,(nxt_c+1)%5])
      # both in same column
      elif prv_c == nxt_c:
        ciphertext += num_to_ltr(key[(prv_r+1)%5,prv_c])
        ciphertext += num_to_ltr(key[(nxt_r+1)%5,nxt_c])
      else:
        ciphertext += num_to_ltr(key[prv_r,nxt_c])
        ciphertext += num_to_ltr(key[nxt_r,prv_c])
    return ciphertext

  def decrypt(self, ciphertext, key):
    plaintext = ''
    # string to list of chars
    ciphertext = [*ciphertext]

    for i in range(1,len(ciphertext), 2):
      prv = ltr_to_num(ciphertext[i-1])
      prv_r,prv_c = np.where(key == ('i' if prv == 'j' else prv))
      nxt = ltr_to_num(ciphertext[i])
      nxt_r,nxt_c = np.where(key == ('i' if nxt == 'j' else nxt))
      # both in same row
      if prv_r == nxt_r:
        plaintext += num_to_ltr(key[prv_r,(prv_c-1)%5])
        plaintext += num_to_ltr(key[nxt_r,(nxt_c-1)%5])
      # both in same column
      elif prv_c == nxt_c:
        plaintext += num_to_ltr(key[(prv_r-1)%5,prv_c])
        plaintext += num_to_ltr(key[(nxt_r-1)%5,nxt_c])
      else:
        plaintext += num_to_ltr(key[prv_r,nxt_c])
        plaintext += num_to_ltr(key[nxt_r,prv_c])
    return plaintext


print("encrypt 'Hello', key=default =>", PlayfairCipher().encrypt('hello', create_pc_key()))
print("decrypt 'ecqzbx', key=default =>", PlayfairCipher().decrypt('ecqzbx', create_pc_key()))

print("encrypt 'The key is hidden under the doorpad', key='guidance' =>", PlayfairCipher().encrypt('The key is hidden under the doorpad', create_pc_key('guidance')))
print("decrypt 'poclbxdrlgiyibcgbglxpobilzlttgiy', key=default =>", PlayfairCipher().decrypt('poclbxdrlgiyibcgbglxpobilzlttgiy', create_pc_key('guidance')))

encrypt 'Hello', key=default => ecqzbx
decrypt 'ecqzbx', key=default => helxlo
encrypt 'The key is hidden under the doorpad', key='guidance' => poclbxdrlgiyibcgbglxpobilzlttgiy
decrypt 'poclbxdrlgiyibcgbglxpobilzlttgiy', key=default => thekeyishidxdenunderthedoxorpadx


In [37]:
keyword = 'manchesterbluffs'
message = 'Playfair'
print(PlayfairCipher().encrypt(message, create_pc_key(keyword)))

idcwunpe


### Vignere Cipher

$P = P_1P_2P_3...$

$C = C_1C_2C_3...$

$K = (k1,p1,p2,...)$

$C_i = (P_i + k_i) mod 26 ; P_i = (C_i - k_i) mod 26$

can be seen as combinations of m additive ciphers

In [38]:
class VignereCipher:
  def encrypt(self, plaintext, keyword):
    # convert to lowercase,
    # remove spaces
    plaintext = plaintext.lower().replace(' ','')
    keyword = keyword.lower().replace(' ','')

    while len(keyword) < len(plaintext):
      keyword += keyword

    # string to list of chars
    plaintext = [*plaintext]
    keyword = [*keyword]

    # make keyword length equal to plaintext
    keyword = keyword[:len(plaintext)]

    # converting to chars to number equivalent
    plaintext = np.array([ltr_to_num(x) for x in plaintext])
    keyword = np.array([ltr_to_num(x) for x in keyword])

    ciphertext = (plaintext + keyword) % 26

    ciphertext = ''.join([num_to_ltr(x) for x in ciphertext])

    return ciphertext

  def decrypt(self, ciphertext, keyword):
    
    while len(keyword) < len(ciphertext):
      keyword += keyword

    # string to list of chars
    ciphertext = [*ciphertext]
    keyword = [*keyword]

    # make keyword length equal to ciphertext
    keyword = keyword[:len(ciphertext)]

    # converting to chars to number equivalent
    ciphertext = np.array([ltr_to_num(x) for x in ciphertext])
    keyword = np.array([ltr_to_num(x) for x in keyword])

    plaintext = ((ciphertext+26) - keyword)%26
    plaintext = ''.join([num_to_ltr(x) for x in plaintext])
    return plaintext


print("encrypt 'She is listening', key='Pascal' =>", VignereCipher().encrypt('She is listening', 'Pascal'))
print("decrypt 'hhwkswxslgntcg', key=pascal =>", VignereCipher().decrypt('hhwkswxslgntcg', 'pascal'))

encrypt 'She is listening', key='Pascal' => hhwkswxslgntcg
decrypt 'hhwkswxslgntcg', key=pascal => sheislistening


### Hill Cipher

Key matrix needs to have a multiplicative inverse.

- C = P*K
- P = C*(1/K)

In [39]:
# for alphabets
def inverse_matrix(x):
  determinant = np.linalg.det(x)
  return determinant

arr = np.array([[3,2],[5,7]])
# np.array([9,7,11,13,4,7,5,6,2,21,14,9,3,23,21,8]).reshape(4,4)
print(inverse_matrix(arr))

11.000000000000002


In [0]:
import math
class HillCipher:
  def encrypt(self, plaintext, keyword):
    # convert to lowercase,
    # remove spaces
    plaintext = plaintext.lower().replace(' ','')
    keyword = keyword.lower().replace(' ','')

    while len(keyword) < len(plaintext):
      keyword += keyword

    # string to list of chars
    plaintext = [*plaintext]
    keyword = [*keyword]

    # make keyword length equal to plaintext
    keyword = keyword[:len(plaintext)]

    # converting to chars to number equivalent
    plaintext = np.array([ltr_to_num(x) for x in plaintext])
    keyword = np.array([ltr_to_num(x) for x in keyword])

    ciphertext = (plaintext + keyword) % 26

    ciphertext = ''.join([num_to_ltr(x) for x in ciphertext])

    return ciphertext

  def decrypt(self, ciphertext, keyword):
    
    while len(keyword) < len(ciphertext):
      keyword += keyword

    # string to list of chars
    ciphertext = [*ciphertext]
    keyword = [*keyword]

    # make keyword length equal to ciphertext
    keyword = keyword[:len(ciphertext)]

    # converting to chars to number equivalent
    ciphertext = np.array([ltr_to_num(x) for x in ciphertext])
    keyword = np.array([ltr_to_num(x) for x in keyword])

    plaintext = ((ciphertext+26) - keyword)%26
    plaintext = ''.join([num_to_ltr(x) for x in plaintext])
    return plaintext

  def g_encrypt(self, plaintext, keyword, n_row):
    # convert to lowercase,
    # remove spaces
    plaintext = plaintext.lower().replace(' ','')
    keyword = keyword.lower().replace(' ','')

    n_col = math.ceil(len(plaintext)/n_row)
    z = 'z'*(n_col - len(plaintext)%n_col)

    plaintext += z
    pt = np.array([ltr_to_num(x) for x in plaintext]).reshape(n_row, n_col)
    kw = np.array([ltr_to_num(x) for x in keyword]).reshape(n_col, n_col)
    #print(np.linalg.inv(kw))
    ct = np.matmul(pt,kw)
    print(ct,pt,kw)
    ct  = ct%26
    
    ciphertext = ct.flatten('C').tolist()
    ciphertext = ''.join([num_to_ltr(x) for x in ciphertext])
    
    return ciphertext

  def g_decrypt(self, ciphertext, keyword, n_row):
    # convert to lowercase,
    # remove spaces
    ciphertext = ciphertext.lower().replace(' ','')
    keyword = keyword.lower().replace(' ','')

    n_col = math.ceil(len(ciphertext)/n_row)
    # z = 'z'*(n_col - len(plaintext)%n_col)

    #plaintext += z
    ct = np.array([ltr_to_num(x) for x in ciphertext]).reshape(n_row, n_col)
    kw = np.array([ltr_to_num(x) for x in keyword]).reshape(n_col, n_col)
    kwi = np.linalg.inv(kw)
    pt = np.matmul(ct,kwi)
    print(pt,ct,kwi)
    pt  = pt%26
    
    plaintext = pt.flatten('C').tolist()
    plaintext = ''.join([num_to_ltr(x) for x in plaintext])
    
    return plaintext


In [41]:
# Wrong
print("encrypt 'She is listening', key='Pascal' =>", HillCipher().encrypt('She is listening', 'Pascal'))
print("decrypt 'hhwkswxslgntcg', key=pascal =>", HillCipher().decrypt('hhwkswxslgntcg', 'pascal'))

# Right
keyword = "".join([num_to_ltr(x) for x in [9,7,11,13,4,7,5,6,2,21,14,9,3,23,21,8]])
print("encrypt 'code is ready', key='"+keyword+"'", HillCipher().g_encrypt('code is ready', keyword, 3))

encrypt 'She is listening', key='Pascal' => hhwkswxslgntcg
decrypt 'hhwkswxslgntcg', key=pascal => sheislistening
[[  92  267  218  169]
 [ 190  631  500  397]
 [ 135 1100  876  434]] [[ 2 14  3  4]
 [ 8 18 17  4]
 [ 0  3 24 25]] [[ 9  7 11 13]
 [ 4  7  5  6]
 [ 2 21 14  9]
 [ 3 23 21  8]]
encrypt 'code is ready', key='jhlnehfgcvojdxvi' ohknihghfiss


In [42]:
keyword = "".join([num_to_ltr(x) for x in [9,7,11,13,4,7,5,6,2,21,14,9,3,23,21,8]])
print("encrypt 'code is ready', key='"+keyword+"'", HillCipher().encrypt('code is ready', keyword))

encrypt 'code is ready', key='jhlnehfgcvojdxvi' lvormzwkcym


In [43]:
#WRONG
msg = 'We live in an insecure world'
kw = ''.join([num_to_ltr(x) for x in [3,2,5,7]])
print("encrypt '"+msg+"', key='"+kw+"' =>", HillCipher().encrypt(msg, kw))

encrypt 'We live in an insecure world', key='dcfh' => zgqpygnudpnuvghbugbvuni


In [44]:
#CORRECT
msg = 'We live in an insecure world'
kw = ''.join([num_to_ltr(x) for x in [3,5,2,7]])
print("encrypt '"+msg+"', key='"+kw+"' =>", HillCipher().g_encrypt(msg, kw, 12))
dmsg = 'wixhtdybanybkouuhjqavghi'
# print("decrypt '"+dmsg+"', key='"+kw+"' =>", HillCipher().g_decrypt(dmsg, kw, 12))

[[ 74 138]
 [ 49 111]
 [ 71 133]
 [ 50 131]
 [ 26  91]
 [ 50 131]
 [ 62 118]
 [ 46 150]
 [ 59 113]
 [ 94 208]
 [ 73 162]
 [ 59 190]] [[22  4]
 [11  8]
 [21  4]
 [ 8 13]
 [ 0 13]
 [ 8 13]
 [18  4]
 [ 2 20]
 [17  4]
 [22 14]
 [17 11]
 [ 3 25]] [[3 5]
 [2 7]]
encrypt 'We live in an insecure world', key='dfch' => wixhtdybanybkouuhjqavghi


### One-Time Pad

One of the goals of cryptography is perfect secrecy. A study by Shannon has shown that perfect secrecy can be achieved if each plaintext symbol is encrypted with a key randomly chosen from a key domain. This idea is used in a cipher called one-time pad, invented by Vernam. 

**Rotor Cipher**

![Rotor Cipher](https://drive.google.com/uc?id=1A2rDoGlWifi7wKhaSdFiX0xIv-dyoHym)

**Enigma Machine**

![Enigma Machine](https://drive.google.com/uc?id=1_h6_VJbxLrGLarJUGItHCAB2EzR4aA68)



## Transposition Ciphers

### Keyless Transposition Ciphers

*Method 1:* 
- Text is written into a table column by column
- transmitted row by row

*Method 2:* 
- Text is written into a table row by row
- transmitted column by column

In [45]:
message = "Meet me at the park"
message = message.lower().replace(" ",'')
print(message, len(message))
# method 1
print(message[0:15:2] + message[1:15:2])
#method 2
print(message[0:15:4] + message[1:15:4] + message[2:15:4] + message[3:15:4])

meetmeatthepark 15
memateaketethpr
mmtaeehreaekttp


### Keyed Transposition Cipher

In [0]:
class KeyedTranspositionCipher:
  def encrypt(plaintext, group_size, key):
    plaintext = plaintext.replace(' ','').lower()
    z = 'z'*(group_size - len(plaintext)%group_size)
    plaintext += z
    key = [int(k) for k in key[1:len(key)-1].split(',')]
    ciphertext = ''
    for start in range(0, len(plaintext), group_size):
      group = plaintext[start:start + group_size]
      for k in key:
        try:
          ciphertext += group[k-1]
        except:
          pass
    return ciphertext

  def decrypt(ciphertext, group_size, key):
    ciphertext = ciphertext.replace(' ','').lower()
    key = [int(k) for k in key[1:len(key)-1].split(',')]
    plaintext=''
    for start in range(0, len(ciphertext), group_size):
      group = ciphertext[start:start + group_size]
      pgroup = 'zzzzz'
      for k, i in enumerate(key):
        try:
          pgroup = pgroup[:i-1] + group[k] + pgroup[i:]
          
        except:
          pass
      plaintext += pgroup
    return plaintext




In [0]:
#@title Encryption - Decryption Key
#@markdown #### Encryption

plaintext = 'Enemy attacks tonight'  #@param {type: "string"}
group_size =   5  #@param {type: "number"}
key = '[3,1,4,5,2]'   #@param {type: "string"}
#@markdown ---


#@markdown #### Decryption

ciphertext = 'eemyntaacttkonshitzg'  #@param {type: "string"}
group_size =   5  #@param {type: "number"}
key = '[3,1,4,5,2]'   #@param {type: "string"}
#@markdown ---


In [48]:
print('Ciphertext',KeyedTranspositionCipher.encrypt(plaintext, group_size, key))
print('Plaintext',KeyedTranspositionCipher.decrypt(ciphertext, group_size, key))

Ciphertext eemyntaacttkonshitzg
Plaintext enemyattackstonightz


Combining Keyless and keyes transposition

In [49]:
print('Ciphertext',KeyedTranspositionCipher.encrypt(plaintext, group_size, key))

Ciphertext eemyntaacttkonshitzg


### Using Matrices

### Double transposition cipher

## Stream and Block Ciphers

### Stream cipher
![stream cipher](https://drive.google.com/uc?id=1TyAt8Ij80GfKxQRenWE1LGJIgHL5Z7UA)

$P = P_1P_2P_3...$

$C = C_1C_2C_3...$

$K = (k1,k2,k3,...)$

$C_i = E_k(P_i)$

#### Examples
- *Additive cipher* $K=(k,k,...)$ [**Monoalphabetic**]
- *Monoalphabetic substitution cipher* 
- *Vignere cipher*  $K=(k_1,k_2,...k_m, k_2,....k_m, ...)$ [**Polyalphabetic**]
- We can say that a stream cipher is a monoalphabetic cipher if the value of ki does not depend on the position of the plaintext character in the plaintext stream; otherwise, the cipher is polyalphabetic

### Block cipher
In a block cipher, a group of plaintext symbols of size m (m > 1) are encrypted together creating a group of ciphertext of the same size. A single key is used to encrypt the whole block even if the key is made of multiple values
![block cipher](https://drive.google.com/uc?id=1CUcep_h1eh8N9-c8XBM1h4DerUKSkSjN)

#### Examples
- *Playfair cipher* block size m=2
- *Hill cipher* block size, m>=2, singel key (m*m matrix)
- *polyalphabetic cipher*

### Combination
In practice, blocks of plaintext are encrypted individually, but they use a stream of keys to encrypt the whole message block by block. In other words, the cipher is a block cipher when looking at the individual blocks, but it is a stream cipher when looking at the whole message considering each block as a single unit. 
